# Generated by Django 5.2.7 on 2025-11-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                PRAGMA foreign_keys=off;
                ALTER TABLE accounts_profile RENAME TO accounts_profile__old;
                CREATE TABLE accounts_profile (
                    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                    avatar VARCHAR(100) NOT NULL,
                    bio TEXT NOT NULL,
                    location VARCHAR(100) NOT NULL,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL,
                    user_id BIGINT NOT NULL UNIQUE,
                    FOREIGN KEY(user_id) REFERENCES accounts_customuser(id)
                        DEFERRABLE INITIALLY DEFERRED
                );
                INSERT INTO accounts_profile (
                    id, avatar, bio, location, created_at, updated_at, user_id
                )
                SELECT
                    id, avatar, bio, location, created_at, updated_at, user_id
                FROM accounts_profile__old;
                DROP TABLE accounts_profile__old;
                PRAGMA foreign_keys=on;
            """,
            reverse_sql="""
                PRAGMA foreign_keys=off;
                ALTER TABLE accounts_profile ADD COLUMN location_coordinates VARCHAR(63) NOT NULL DEFAULT '';
                PRAGMA foreign_keys=on;
            """,
        ),
    ]
