# Generated by Django 5.2.7 on 2025-10-31 15:15

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_job_experience_level_job_salary_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
